
daddonmap.title.text=Mapa veľkostí doplnkov
daddonmap.sizefilter.text=Maximálny filter veľkosti (MB)
daddonmap.generate.text=Dvakrát kliknite na vygenerovanie mapy veľkostí doplnkov
daddonmap.generate.warning=Toto je náročný proces; záťaž bude závisieť od počtu doplnkov.
