
daddonmap.title.text=Tilläggsstorlekskarta
daddonmap.sizefilter.text=Maximal storleksfilter (MB)
daddonmap.generate.text=Klicka två gånger för att generera tilläggsstorlekskartan
daddonmap.generate.warning=Detta är en intensiv process; belastningen beror på antalet tillägg.
