
daddonmap.title.text=Mapa velikosti doplňků
daddonmap.sizefilter.text=Maximální filtr velikosti (MB)
daddonmap.generate.text=Klikněte dvakrát pro vygenerování mapy velikosti doplňků
daddonmap.generate.warning=Toto je náročný proces, zatížení bude záviset na počtu doplňků.
