
daddonmap.title.text=Lisandmooduli suuruse kaart
daddonmap.sizefilter.text=Maksimaalne suurusfilter (MB)
daddonmap.generate.text=Klõpsake kaks korda lisandmooduli suuruse kaardi loomiseks
daddonmap.generate.warning=See on ressursimahukas protsess; koormus sõltub lisandmoodulite arvust.
