
daddonmap.title.text=Kart over tilleggsstørrelser
daddonmap.sizefilter.text=Maks. størrelsesfilter (MB)
daddonmap.generate.text=Klikk to ganger for å generere kart over tilleggsstørrelser
daddonmap.generate.warning=Dette er en krevende prosess; belastningen avhenger av antall tillegg.
