
daddonmap.title.text=מפת גודל תוספות
daddonmap.sizefilter.text=מסנן גודל מקסימלי (MB)
daddonmap.generate.text=לחץ פעמיים כדי ליצור מפת גודל תוספות
daddonmap.generate.warning=זהו תהליך אינטנסיבי, העומס יהיה תלוי במספר התוספות.
