
daddonmap.title.text=Карта на размера на добавките
daddonmap.sizefilter.text=Максимален филтър за размер (МБ)
daddonmap.generate.text=Натиснете двукратно за генериране на карта на размера на добавките
daddonmap.generate.warning=Това е интензивен процес, натоварването ще зависи от броя на добавките.
