
daddonmap.title.text=Priedų dydžių žemėlapis
daddonmap.sizefilter.text=Maksimalus dydžio filtras (MB)
daddonmap.generate.text=Spustelėkite du kartus, kad sugeneruotumėte priedų dydžių žemėlapį
daddonmap.generate.warning=Tai intensyvus procesas; apkrova priklausys nuo priedų skaičiaus.
