
daddonmap.title.text=Eklenti Boyut Haritası
daddonmap.sizefilter.text=Maksimum Boyut Filtresi (MB)
daddonmap.generate.text=Eklenti boyut haritası oluşturmak için iki kez tıklayın
daddonmap.generate.warning=Bu yoğun bir işlemdir; yük, eklenti sayısına bağlı olacaktır.
