
daddonmap.title.text=Tilføjelses-størrelseskort
daddonmap.sizefilter.text=Maks. størrelsesfilter (MB)
daddonmap.generate.text=Klik to gange for at generere tilføjelses-størrelseskort
daddonmap.generate.warning=Dette er en krævende proces; belastningen afhænger af antallet af tilføjelser.
