
daddonmap.title.text=Kiegészítő mérettérkép
daddonmap.sizefilter.text=Maximális méretszűrő (MB)
daddonmap.generate.text=Kattintson kétszer a kiegészítő mérettérkép létrehozásához
daddonmap.generate.warning=Ez egy intenzív folyamat; a terhelés a kiegészítők számától függ.
