
daddonmap.title.text=Mapa rozmiarów dodatków
daddonmap.sizefilter.text=Maksymalny filtr rozmiaru (MB)
daddonmap.generate.text=Kliknij dwukrotnie, aby wygenerować mapę rozmiarów dodatków
daddonmap.generate.warning=Jest to intensywny proces; obciążenie będzie zależeć od liczby dodatków.
