
daddonmap.title.text=Lisäosan kokokartta
daddonmap.sizefilter.text=Enimmäiskokosuodatin (Mt)
daddonmap.generate.text=Luo lisäosan kokokartta kaksoisnapsauttamalla
daddonmap.generate.warning=Tämä on raskas prosessi; kuormitus riippuu lisäosien määrästä.
