
daddonmap.title.text=Karta veličine dodataka
daddonmap.sizefilter.text=Maksimalni filter veličine (MB)
daddonmap.generate.text=Kliknite dvaput za generiranje karte veličine dodataka
daddonmap.generate.warning=Ovo je intenzivan proces; opterećenje će ovisiti o broju dodataka.
