
daddonmap.title.text=แผนที่ขนาดแอดออน
daddonmap.sizefilter.text=ตัวกรองขนาดสูงสุด (MB)
daddonmap.generate.text=คลิกสองครั้งเพื่อสร้างแผนที่ขนาดแอดออน
daddonmap.generate.warning=นี่เป็นกระบวนการที่เข้มข้น ปริมาณงานจะขึ้นอยู่กับจำนวนแอดออน
