
daddonmap.title.text=Addon-Größenkarte
daddonmap.sizefilter.text=Maximaler Größenfilter (MB)
daddonmap.generate.text=Zweimal klicken, um die Addon-Größenkarte zu erstellen
daddonmap.generate.warning=Dies ist ein rechenintensiver Vorgang; die Last hängt von der Anzahl der Addons ab.
