
daddonmap.title.text=Карта розмірів доповнень
daddonmap.sizefilter.text=Максимальний фільтр розміру (МБ)
daddonmap.generate.text=Натисніть двічі для створення карти розмірів доповнень
daddonmap.generate.warning=Це ресурсомісткий процес; навантаження залежатиме від кількості доповнень.
