
daddonmap.title.text=Mapa de tamanho de addons
daddonmap.sizefilter.text=Filtro de tamanho máximo (MB)
daddonmap.generate.text=Clique duas vezes para gerar o mapa de tamanho de addons
daddonmap.generate.warning=Este é um processo intensivo; a carga dependerá do número de addons.
