
daddonmap.title.text=Addon-groottekaart
daddonmap.sizefilter.text=Maximale groottefilter (MB)
daddonmap.generate.text=Klik twee keer om de addon-groottekaart te genereren
daddonmap.generate.warning=Dit is een intensief proces; de belasting hangt af van het aantal addons.
