
daddonmap.title.text=Mapa de tamaño de complementos
daddonmap.sizefilter.text=Filtro de tamaño máximo (MB)
daddonmap.generate.text=Haz clic dos veces para generar el mapa de tamaño de complementos
daddonmap.generate.warning=Este es un proceso intensivo; la carga dependerá del número de complementos.
