
daddonmap.title.text=Карта размеров дополнений
daddonmap.sizefilter.text=Максимальный фильтр размера (МБ)
daddonmap.generate.text=Нажмите дважды для создания карты размеров дополнений
daddonmap.generate.warning=Это ресурсоёмкий процесс; нагрузка будет зависеть от количества дополнений.
