
daddonmap.title.text=Addon Size Map
daddonmap.sizefilter.text=Max Size Filter (MB)
daddonmap.generate.text=Click twice to generate addon size map
daddonmap.generate.warning=This is an intensive process, load will depend on number of addons.
