
daddonmap.title.text=Addon Booty Map
daddonmap.sizefilter.text=Max Plunder Size Filter (MB)
daddonmap.generate.text=Click twice, ye scallywag, to chart the addon booty map
daddonmap.generate.warning=Blimey! This be an intensive voyage, the load depends on how many addons ye be carryin'.
