
daddonmap.title.text=Χάρτης μεγέθους πρόσθετων
daddonmap.sizefilter.text=Μέγιστο φίλτρο μεγέθους (MB)
daddonmap.generate.text=Κάντε διπλό κλικ για δημιουργία χάρτη μεγέθους πρόσθετων
daddonmap.generate.warning=Αυτή είναι μια εντατική διαδικασία, το φορτίο θα εξαρτηθεί από τον αριθμό των πρόσθετων.
