
daddonmap.title.text=Mappa dimensioni addon
daddonmap.sizefilter.text=Filtro dimensione massima (MB)
daddonmap.generate.text=Fare doppio clic per generare la mappa delle dimensioni degli addon
daddonmap.generate.warning=Questo è un processo intensivo; il carico dipenderà dal numero di addon.
