
daddonmap.title.text=Bản đồ kích thước addon
daddonmap.sizefilter.text=Bộ lọc kích thước tối đa (MB)
daddonmap.generate.text=Nhấp hai lần để tạo bản đồ kích thước addon
daddonmap.generate.warning=Đây là một quá trình đòi hỏi nhiều tài nguyên, tải sẽ phụ thuộc vào số lượng addon.
