
daddonmap.title.text=Carte des tailles d'extensions
daddonmap.sizefilter.text=Filtre de taille maximale (Mo)
daddonmap.generate.text=Cliquez deux fois pour générer la carte des tailles d'extensions
daddonmap.generate.warning=Il s'agit d'un processus intensif ; la charge dépendra du nombre d'extensions.
